<img src="exam_result.jpeg" alt="exam_result image" width="49%"/> <img src="examB.png" alt="Lower exam grade image" width="49%"/>

In today's fast-paced and competitive educational environment, understanding the factors that influence student success is more important than ever. Just like the transport system in a bustling city like London must adapt to serve its residents, schools and educators must adapt to meet the needs of students. In this project, we will take a deep dive into a dataset containing rich details about various aspects of student life, such as hours studied, sleep patterns, attendance, and more, to uncover what truly impacts exam performance.

The dataset we'll be working with includes a wide range of factors influencing student performance. By analyzing this data, we'll be able to identify key drivers of success and provide insights that could help students, teachers, and policymakers make informed decisions. The table we'll use for this project is called `student_performance` and includes the following data:

| Column                   | Definition                                                      | Data type             |
|--------------------------|-----------------------------------------------------------------|-----------------------|
| `attendance`              | Percentage of classes attended                                  |     `float`               |
| `extracurricular_activities` | Participation in extracurricular activities                   |     `varchar` (Yes, No)    |
| `sleep_hours`             | Average number of hours of sleep per night                      |     `float`               |
| `tutoring_sessions`       | Number of tutoring sessions attended per month                  |     `integer`             |
| `teacher_quality`         | Quality of the teachers                                         |     `varchar` (Low, Medium, High) |
| `exam_score`              | Final exam score                                                |     `float`               |

You will execute SQL queries to answer three questions, as listed in the instructions.

In [50]:
-- avg_exam_score_by_study_and_extracurricular
-- Edit the query below as needed
SELECT hours_studied, avg(exam_score) as avg_exam_score
FROM student_performance
where hours_studied > 10
and extracurricular_activities = 'Yes'
group by hours_studied
order by hours_studied desc

    hours_studied  avg_exam_score
0              43       78.000000
1              39       75.000000
2              38       73.500000
3              37       73.000000
4              36       70.428571
5              35       72.312500
6              34       71.187500
7              33       70.333333
8              32       71.325000
9              31       70.553191
10             30       71.432836
11             29       70.256098
12             28       69.825688
13             27       69.776860
14             26       68.801370
15             25       69.000000
16             24       68.483871
17             23       68.207469
18             22       67.721519
19             21       67.710425
20             20       67.218638
21             19       67.211765
22             18       67.024000
23             17       66.401826
24             16       66.586047
25             15       65.901099
26             14       65.862275
27             13       64.976190
28             12       64.966102
29             11       65.145833

In [51]:
-- avg_exam_score_by_hours_studied_range
-- Add solution code below 
select
case 
when hours_studied between 1 and 5 then '1-5 hours'
when hours_studied between 6 and 10 then '6-10 hours'
when hours_studied between 11 and 15 then '11-15 hours'
when hours_studied >= 16 then '16+ hours'
end as hours_studied_range, avg(exam_score) as avg_exam_score
from student_performance
group by hours_studied_range
order by avg(exam_score) desc

  hours_studied_range  avg_exam_score
0           16+ hours       67.923363
1         11-15 hours       65.204386
2          6-10 hours       64.225490
3           1-5 hours       62.627119

In [52]:
-- student_exam_ranking
-- Add solution code below 
select attendance, hours_studied, sleep_hours, tutoring_sessions, dense_rank() over (order by exam_score desc) as exam_rank
from student_performance
limit 30

    attendance  hours_studied  sleep_hours  tutoring_sessions  exam_rank
0           98             27            6                  5          1
1           89             18            4                  3          2
2           90             14            8                  4          3
3           83             23            4                  1          3
4           83             16            8                  2          4
5           96             28            4                  1          4
6           90             28            9                  0          4
7           74             21            6                  1          5
8           99             25            7                  0          5
9           83             15            7                  2          5
10          93             18            7                  2          6
11          67             21            6                  1          7
12          90             18            6                  1          7
13          76             29            8                  2          8
14          96             24            6                  2          8
15          98             25            7                  1          8
16          90             19            5                  0          8
17          69             26            7                  0          9
18          73             25            7                  2          9
19          69             31            7                  2         10
20          88              1            4                  3         10
21          70             21            9                  1         11
22          92             21            9                  2         12
23          77             14            6                  1         12
24          70             19            7                  0         12
25          62             11            7                  3         13
26          86             18            8                  2         13
27          98             30            9                  1         13
28          69              7            8                  1         14
29          71             11            8                  1         14

In [1]:
-- Explore the data in the table
SELECT *
FROM public.student_performance
LIMIT 50

    hours_studied  attendance  ... tutoring_sessions  exam_score
0              23          84  ...                 0          67
1              19          64  ...                 2          61
2              24          98  ...                 2          74
3              29          89  ...                 1          71
4              19          92  ...                 3          70
5              19          88  ...                 3          71
6              29          84  ...                 1          67
7              25          78  ...                 1          66
8              17          94  ...                 0          69
9              23          98  ...                 0          72
10             17          80  ...                 4          68
11             17          97  ...                 2          71
12             21          83  ...                 2          70
13              9          82  ...                 2          66
14             10          78  ...                 1          65
15             17          68  ...                 2          64
16             14          60  ...                 0          60
17             22          70  ...                 1          65
18             15          80  ...                 3          67
19             12          75  ...                 3          66
20             29          78  ...                 0          69
21             19          99  ...                 1          72
22             20          74  ...                 1          66
23             11          78  ...                 1          66
24             17          65  ...                 2          63
25             21          62  ...                 0          64
26             13          91  ...                 1          65
27             22          83  ...                 0          71
28             16          90  ...                 1          66
29             18          66  ...                 2          64
30             16          83  ...                 0          63
31             31          70  ...                 1          69
32             20          69  ...                 2          67
33             14          60  ...                 2          61
34             25          65  ...                 2          68
35             13          72  ...                 1          61
36             21          65  ...                 2          64
37              8          99  ...                 2          67
38             12          72  ...                 1          63
39             21          65  ...                 1          64
40             24          68  ...                 3          67
41             21          84  ...                 1          65
42             19          63  ...                 1          64
43             18          94  ...                 3          70
44             11          98  ...                 1          68
45             16          70  ...                 2          65
46             17          78  ...                 1          68
47             26          61  ...                 2          64
48             22          86  ...                 3          68
49              9          77  ...                 2          63

[50 rows x 6 columns]