![baby_names](baby_names.jpg)

How have American baby name tastes changed since 1920? Which names have remained popular for over 100 years, and how do those names compare to more recent top baby names? These are considerations for many new parents, but the skills you'll practice while answering these queries are broadly applicable. After all, understanding trends and popularity is important for many businesses, too!

You'll be working with data provided by the United States Social Security Administration, which lists first names along with the number and sex of babies they were given to in each year. For processing speed purposes, the dataset is limited to first names which were given to over 5,000 American babies in a given year. The data spans 101 years, from 1920 through 2020.

## The Data

### `baby_names`

| column         | type    | description                                                                  |
| -------------- | ------- | ------------------------------------------------------------------------ |
| `year`         | int     | year                                                                     |
| `first_name`   | varchar | first name                                                               |
| `sex`          | varchar | `sex` of babies given `first_name`                                       |
| `num`          | int     | number of babies of `sex` given `first_name` in that `year`              |

In [76]:
-- Run this code to view the data in baby_names
select * from baby_names
where first_name = 'Emma'

    year first_name sex    num
0   1920       Emma   F   5237
1   1921       Emma   F   5073
2   1922       Emma   F   5013
3   1995       Emma   F   5047
4   1996       Emma   F   6144
5   1997       Emma   F   7746
6   1998       Emma   F  10446
7   1999       Emma   F  11740
8   2000       Emma   F  12556
9   2001       Emma   F  13316
10  2002       Emma   F  16546
11  2003       Emma   F  22709
12  2004       Emma   F  21611
13  2005       Emma   F  20348
14  2006       Emma   F  19120
15  2007       Emma   F  18377
16  2008       Emma   F  18817
17  2009       Emma   F  17905
18  2010       Emma   F  17351
19  2011       Emma   F  18808
20  2012       Emma   F  20954
21  2013       Emma   F  20950
22  2014       Emma   F  20943
23  2015       Emma   F  20465
24  2016       Emma   F  19522
25  2017       Emma   F  19837
26  2018       Emma   F  18770
27  2019       Emma   F  17155
28  2020       Emma   F  15581

In [77]:
-- Use this table for the answer to question 1:
-- List the overall top five names in alphabetical order and find out if each name is "Classic" or "Trendy."
select first_name, count(year) as sum, case 
	when count(year) > 50 then 'Classic'
	else 'Trendy'
	end as popularity_type
from baby_names
group by first_name
	order by first_name
limit 5

  first_name  sum popularity_type
0    Aaliyah    3          Trendy
1      Aaron   51         Classic
2    Abigail   28          Trendy
3       Adam   46          Trendy
4    Addison   13          Trendy

In [78]:
-- Use this table for the answer to question 2:
-- What were the top 20 male names overall, and how did the name Paul rank?
select dense_rank () over (partition by sex order by count(first_name)desc) as name_rank, first_name, count(first_name) as sum
from baby_names 
where sex = 'M'
group by first_name, sex
	order by count(first_name) desc
limit 20

    name_rank   first_name  sum
0           1      William  101
1           1        James  101
2           1       Thomas  101
3           1       Joseph  101
4           1         John  101
5           1      Charles  101
6           1        David  101
7           2       Robert   99
8           3      Anthony   86
9           4      Michael   85
10          5       Daniel   84
11          5      Richard   84
12          6         Paul   76
13          6      Kenneth   76
14          7       Edward   73
15          8  Christopher   70
16          8       Andrew   70
17          9       Donald   65
18          9        Kevin   65
19         10      Matthew   64

In [79]:
-- Use this table for the answer to question 3:
-- Which female names appeared in both 1920 and 2020?
with cte as (select first_name, num
	from baby_names
	where year = 1920
	and sex = 'F'),
cte2 as (select first_name, num
	from baby_names 
	where year = 2020
	and sex = 'F')

select cte.first_name, (cte.num + cte2.num) as total_occurrences
from cte
join cte2 on cte.first_name = cte2.first_name

  first_name  total_occurrences
0       Emma              20818
1     Evelyn              23283
2  Elizabeth              23125
3    Eleanor              14832
4      Grace              12741
5      Hazel              12765

In [1]:
-- Explore the data in the table
SELECT *
FROM public.baby_names
LIMIT 50

    year first_name sex    num
0   1920       Mary   F  70982
1   1920    Dorothy   F  36643
2   1920      Helen   F  35097
3   1920   Margaret   F  27994
4   1920       Ruth   F  26101
5   1920    Mildred   F  18059
6   1920   Virginia   F  17314
7   1920  Elizabeth   F  15909
8   1920    Frances   F  15883
9   1920       Anna   F  14581
10  1920      Betty   F  14016
11  1920     Evelyn   F  13838
12  1920      Marie   F  12743
13  1920      Doris   F  11892
14  1920      Alice   F  11596
15  1920   Florence   F  10732
16  1920      Irene   F  10072
17  1920    Lillian   F  10049
18  1920     Louise   F   9179
19  1920       Rose   F   9011
20  1920  Catherine   F   8878
21  1920     Gladys   F   8819
22  1920     Martha   F   8709
23  1920   Marjorie   F   8658
24  1920    Eleanor   F   8497
25  1920       Ruby   F   8336
26  1920       Edna   F   8331
27  1920  Josephine   F   8093
28  1920    Lucille   F   7989
29  1920      Ethel   F   7868
30  1920     Thelma   F   7814
31  1920      Edith   F   7773
32  1920       Jean   F   7714
33  1920      Hazel   F   7308
34  1920      Annie   F   7269
35  1920    Pauline   F   7180
36  1920      Grace   F   7172
37  1920       Lois   F   6560
38  1920     Esther   F   6068
39  1920    Bernice   F   5928
40  1920   Beatrice   F   5804
41  1920   Gertrude   F   5797
42  1920     Marion   F   5745
43  1920      Clara   F   5470
44  1920  Katherine   F   5276
45  1920       Emma   F   5237
46  1920    Barbara   F   5106
47  1920       Jane   F   5055
48  1920        Ann   F   5041
49  1920      Sarah   F   5031